// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/chronos/v1/chronos.proto

package chronosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED  WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_RUNNING      WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED    WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_FAILED       WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_CANCELLED    WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_COMPENSATING WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_COMPENSATED  WorkflowStatus = 6
	WorkflowStatus_WORKFLOW_STATUS_SCHEDULED    WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_COMPLETED",
		3: "WORKFLOW_STATUS_FAILED",
		4: "WORKFLOW_STATUS_CANCELLED",
		5: "WORKFLOW_STATUS_COMPENSATING",
		6: "WORKFLOW_STATUS_COMPENSATED",
		7: "WORKFLOW_STATUS_SCHEDULED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED":  0,
		"WORKFLOW_STATUS_RUNNING":      1,
		"WORKFLOW_STATUS_COMPLETED":    2,
		"WORKFLOW_STATUS_FAILED":       3,
		"WORKFLOW_STATUS_CANCELLED":    4,
		"WORKFLOW_STATUS_COMPENSATING": 5,
		"WORKFLOW_STATUS_COMPENSATED":  6,
		"WORKFLOW_STATUS_SCHEDULED":    7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED  TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING      TaskStatus = 1
	TaskStatus_TASK_STATUS_READY        TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING      TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED    TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED       TaskStatus = 5
	TaskStatus_TASK_STATUS_CANCELLED    TaskStatus = 6
	TaskStatus_TASK_STATUS_COMPENSATING TaskStatus = 7
	TaskStatus_TASK_STATUS_COMPENSATED  TaskStatus = 8
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_READY",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_CANCELLED",
		7: "TASK_STATUS_COMPENSATING",
		8: "TASK_STATUS_COMPENSATED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":  0,
		"TASK_STATUS_PENDING":      1,
		"TASK_STATUS_READY":        2,
		"TASK_STATUS_RUNNING":      3,
		"TASK_STATUS_COMPLETED":    4,
		"TASK_STATUS_FAILED":       5,
		"TASK_STATUS_CANCELLED":    6,
		"TASK_STATUS_COMPENSATING": 7,
		"TASK_STATUS_COMPENSATED":  8,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{1}
}

type TimerStatus int32

const (
	TimerStatus_TIMER_STATUS_UNSPECIFIED TimerStatus = 0
	TimerStatus_TIMER_STATUS_SCHEDULED   TimerStatus = 1
	TimerStatus_TIMER_STATUS_FIRED       TimerStatus = 2
	TimerStatus_TIMER_STATUS_CANCELLED   TimerStatus = 3
)

// Enum value maps for TimerStatus.
var (
	TimerStatus_name = map[int32]string{
		0: "TIMER_STATUS_UNSPECIFIED",
		1: "TIMER_STATUS_SCHEDULED",
		2: "TIMER_STATUS_FIRED",
		3: "TIMER_STATUS_CANCELLED",
	}
	TimerStatus_value = map[string]int32{
		"TIMER_STATUS_UNSPECIFIED": 0,
		"TIMER_STATUS_SCHEDULED":   1,
		"TIMER_STATUS_FIRED":       2,
		"TIMER_STATUS_CANCELLED":   3,
	}
)

func (x TimerStatus) Enum() *TimerStatus {
	p := new(TimerStatus)
	*p = x
	return p
}

func (x TimerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[2].Descriptor()
}

func (TimerStatus) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[2]
}

func (x TimerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimerStatus.Descriptor instead.
func (TimerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{2}
}

type TimerPurpose int32

const (
	TimerPurpose_TIMER_PURPOSE_UNSPECIFIED    TimerPurpose = 0
	TimerPurpose_TIMER_PURPOSE_WORKFLOW_START TimerPurpose = 1
	TimerPurpose_TIMER_PURPOSE_RETRY          TimerPurpose = 2
	TimerPurpose_TIMER_PURPOSE_TIMEOUT        TimerPurpose = 3
)

// Enum value maps for TimerPurpose.
var (
	TimerPurpose_name = map[int32]string{
		0: "TIMER_PURPOSE_UNSPECIFIED",
		1: "TIMER_PURPOSE_WORKFLOW_START",
		2: "TIMER_PURPOSE_RETRY",
		3: "TIMER_PURPOSE_TIMEOUT",
	}
	TimerPurpose_value = map[string]int32{
		"TIMER_PURPOSE_UNSPECIFIED":    0,
		"TIMER_PURPOSE_WORKFLOW_START": 1,
		"TIMER_PURPOSE_RETRY":          2,
		"TIMER_PURPOSE_TIMEOUT":        3,
	}
)

func (x TimerPurpose) Enum() *TimerPurpose {
	p := new(TimerPurpose)
	*p = x
	return p
}

func (x TimerPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimerPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[3].Descriptor()
}

func (TimerPurpose) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[3]
}

func (x TimerPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimerPurpose.Descriptor instead.
func (TimerPurpose) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{3}
}

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED     CommandKind = 0
	CommandKind_COMMAND_KIND_SUBMIT_WORKFLOW CommandKind = 1
	CommandKind_COMMAND_KIND_START_TASK      CommandKind = 2
	CommandKind_COMMAND_KIND_COMPLETE_TASK   CommandKind = 3
	CommandKind_COMMAND_KIND_FAIL_TASK       CommandKind = 4
	CommandKind_COMMAND_KIND_RENEW_LEASE     CommandKind = 5
	CommandKind_COMMAND_KIND_EXPIRE_LEASE    CommandKind = 6
	CommandKind_COMMAND_KIND_FIRE_TIMER      CommandKind = 7
	CommandKind_COMMAND_KIND_CANCEL_WORKFLOW CommandKind = 8
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_SUBMIT_WORKFLOW",
		2: "COMMAND_KIND_START_TASK",
		3: "COMMAND_KIND_COMPLETE_TASK",
		4: "COMMAND_KIND_FAIL_TASK",
		5: "COMMAND_KIND_RENEW_LEASE",
		6: "COMMAND_KIND_EXPIRE_LEASE",
		7: "COMMAND_KIND_FIRE_TIMER",
		8: "COMMAND_KIND_CANCEL_WORKFLOW",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":     0,
		"COMMAND_KIND_SUBMIT_WORKFLOW": 1,
		"COMMAND_KIND_START_TASK":      2,
		"COMMAND_KIND_COMPLETE_TASK":   3,
		"COMMAND_KIND_FAIL_TASK":       4,
		"COMMAND_KIND_RENEW_LEASE":     5,
		"COMMAND_KIND_EXPIRE_LEASE":    6,
		"COMMAND_KIND_FIRE_TIMER":      7,
		"COMMAND_KIND_CANCEL_WORKFLOW": 8,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[4].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[4]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{4}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED                     EventKind = 0
	EventKind_EVENT_KIND_WORKFLOW_SUBMITTED              EventKind = 1
	EventKind_EVENT_KIND_TASK_READY                      EventKind = 2
	EventKind_EVENT_KIND_TASK_STARTED                    EventKind = 3
	EventKind_EVENT_KIND_TASK_COMPLETED                  EventKind = 4
	EventKind_EVENT_KIND_TASK_FAILED                     EventKind = 5
	EventKind_EVENT_KIND_WORKFLOW_COMPLETED              EventKind = 6
	EventKind_EVENT_KIND_WORKFLOW_FAILED                 EventKind = 7
	EventKind_EVENT_KIND_TASK_LEASE_RENEWED              EventKind = 8
	EventKind_EVENT_KIND_TASK_LEASE_EXPIRED              EventKind = 9
	EventKind_EVENT_KIND_WORKFLOW_STARTED                EventKind = 10
	EventKind_EVENT_KIND_FANOUT_EXPANDED                 EventKind = 11
	EventKind_EVENT_KIND_TIMER_SCHEDULED                 EventKind = 12
	EventKind_EVENT_KIND_TIMER_FIRED                     EventKind = 13
	EventKind_EVENT_KIND_TIMER_CANCELLED                 EventKind = 14
	EventKind_EVENT_KIND_TASK_RETRY_SCHEDULED            EventKind = 15
	EventKind_EVENT_KIND_TASK_TIMED_OUT                  EventKind = 16
	EventKind_EVENT_KIND_TASK_CANCELLED                  EventKind = 17
	EventKind_EVENT_KIND_WORKFLOW_CANCELLATION_REQUESTED EventKind = 18
	EventKind_EVENT_KIND_WORKFLOW_COMPENSATING           EventKind = 19
	EventKind_EVENT_KIND_TASK_COMPENSATED                EventKind = 20
	EventKind_EVENT_KIND_WORKFLOW_CANCELLED              EventKind = 21
	EventKind_EVENT_KIND_WORKFLOW_COMPENSATED            EventKind = 22
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0:  "EVENT_KIND_UNSPECIFIED",
		1:  "EVENT_KIND_WORKFLOW_SUBMITTED",
		2:  "EVENT_KIND_TASK_READY",
		3:  "EVENT_KIND_TASK_STARTED",
		4:  "EVENT_KIND_TASK_COMPLETED",
		5:  "EVENT_KIND_TASK_FAILED",
		6:  "EVENT_KIND_WORKFLOW_COMPLETED",
		7:  "EVENT_KIND_WORKFLOW_FAILED",
		8:  "EVENT_KIND_TASK_LEASE_RENEWED",
		9:  "EVENT_KIND_TASK_LEASE_EXPIRED",
		10: "EVENT_KIND_WORKFLOW_STARTED",
		11: "EVENT_KIND_FANOUT_EXPANDED",
		12: "EVENT_KIND_TIMER_SCHEDULED",
		13: "EVENT_KIND_TIMER_FIRED",
		14: "EVENT_KIND_TIMER_CANCELLED",
		15: "EVENT_KIND_TASK_RETRY_SCHEDULED",
		16: "EVENT_KIND_TASK_TIMED_OUT",
		17: "EVENT_KIND_TASK_CANCELLED",
		18: "EVENT_KIND_WORKFLOW_CANCELLATION_REQUESTED",
		19: "EVENT_KIND_WORKFLOW_COMPENSATING",
		20: "EVENT_KIND_TASK_COMPENSATED",
		21: "EVENT_KIND_WORKFLOW_CANCELLED",
		22: "EVENT_KIND_WORKFLOW_COMPENSATED",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED":                     0,
		"EVENT_KIND_WORKFLOW_SUBMITTED":              1,
		"EVENT_KIND_TASK_READY":                      2,
		"EVENT_KIND_TASK_STARTED":                    3,
		"EVENT_KIND_TASK_COMPLETED":                  4,
		"EVENT_KIND_TASK_FAILED":                     5,
		"EVENT_KIND_WORKFLOW_COMPLETED":              6,
		"EVENT_KIND_WORKFLOW_FAILED":                 7,
		"EVENT_KIND_TASK_LEASE_RENEWED":              8,
		"EVENT_KIND_TASK_LEASE_EXPIRED":              9,
		"EVENT_KIND_WORKFLOW_STARTED":                10,
		"EVENT_KIND_FANOUT_EXPANDED":                 11,
		"EVENT_KIND_TIMER_SCHEDULED":                 12,
		"EVENT_KIND_TIMER_FIRED":                     13,
		"EVENT_KIND_TIMER_CANCELLED":                 14,
		"EVENT_KIND_TASK_RETRY_SCHEDULED":            15,
		"EVENT_KIND_TASK_TIMED_OUT":                  16,
		"EVENT_KIND_TASK_CANCELLED":                  17,
		"EVENT_KIND_WORKFLOW_CANCELLATION_REQUESTED": 18,
		"EVENT_KIND_WORKFLOW_COMPENSATING":           19,
		"EVENT_KIND_TASK_COMPENSATED":                20,
		"EVENT_KIND_WORKFLOW_CANCELLED":              21,
		"EVENT_KIND_WORKFLOW_COMPENSATED":            22,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_chronos_v1_chronos_proto_enumTypes[5].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_api_chronos_v1_chronos_proto_enumTypes[5]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{5}
}

type RetryPolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts          uint32                 `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	InitialBackoffMillis int64                  `protobuf:"varint,2,opt,name=initial_backoff_millis,json=initialBackoffMillis,proto3" json:"initial_backoff_millis,omitempty"`
	BackoffMultiplier    uint32                 `protobuf:"varint,3,opt,name=backoff_multiplier,json=backoffMultiplier,proto3" json:"backoff_multiplier,omitempty"`
	MaxBackoffMillis     int64                  `protobuf:"varint,4,opt,name=max_backoff_millis,json=maxBackoffMillis,proto3" json:"max_backoff_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicy) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoffMillis() int64 {
	if x != nil {
		return x.InitialBackoffMillis
	}
	return 0
}

func (x *RetryPolicy) GetBackoffMultiplier() uint32 {
	if x != nil {
		return x.BackoffMultiplier
	}
	return 0
}

func (x *RetryPolicy) GetMaxBackoffMillis() int64 {
	if x != nil {
		return x.MaxBackoffMillis
	}
	return 0
}

type CompensationDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompensationDefinition) Reset() {
	*x = CompensationDefinition{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationDefinition) ProtoMessage() {}

func (x *CompensationDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationDefinition.ProtoReflect.Descriptor instead.
func (*CompensationDefinition) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{1}
}

func (x *CompensationDefinition) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type FanoutDefinition struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	TaskType        string                  `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	AggregateTaskId string                  `protobuf:"bytes,2,opt,name=aggregate_task_id,json=aggregateTaskId,proto3" json:"aggregate_task_id,omitempty"`
	MaxItems        uint32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	Retry           *RetryPolicy            `protobuf:"bytes,4,opt,name=retry,proto3" json:"retry,omitempty"`
	TimeoutMillis   int64                   `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	Compensation    *CompensationDefinition `protobuf:"bytes,6,opt,name=compensation,proto3" json:"compensation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FanoutDefinition) Reset() {
	*x = FanoutDefinition{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutDefinition) ProtoMessage() {}

func (x *FanoutDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutDefinition.ProtoReflect.Descriptor instead.
func (*FanoutDefinition) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{2}
}

func (x *FanoutDefinition) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *FanoutDefinition) GetAggregateTaskId() string {
	if x != nil {
		return x.AggregateTaskId
	}
	return ""
}

func (x *FanoutDefinition) GetMaxItems() uint32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *FanoutDefinition) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *FanoutDefinition) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *FanoutDefinition) GetCompensation() *CompensationDefinition {
	if x != nil {
		return x.Compensation
	}
	return nil
}

type TaskDefinition struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Dependencies  []string                `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Retry         *RetryPolicy            `protobuf:"bytes,4,opt,name=retry,proto3" json:"retry,omitempty"`
	TimeoutMillis int64                   `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	Compensation  *CompensationDefinition `protobuf:"bytes,6,opt,name=compensation,proto3" json:"compensation,omitempty"`
	Fanout        *FanoutDefinition       `protobuf:"bytes,7,opt,name=fanout,proto3" json:"fanout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{3}
}

func (x *TaskDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskDefinition) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *TaskDefinition) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *TaskDefinition) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *TaskDefinition) GetCompensation() *CompensationDefinition {
	if x != nil {
		return x.Compensation
	}
	return nil
}

func (x *TaskDefinition) GetFanout() *FanoutDefinition {
	if x != nil {
		return x.Fanout
	}
	return nil
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tasks         []*TaskDefinition      `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	StartAt       int64                  `protobuf:"varint,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkflowDefinition) GetTasks() []*TaskDefinition {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *WorkflowDefinition) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

type FanoutItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanoutItem) Reset() {
	*x = FanoutItem{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutItem) ProtoMessage() {}

func (x *FanoutItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutItem.ProtoReflect.Descriptor instead.
func (*FanoutItem) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{5}
}

func (x *FanoutItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FanoutItem) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExpandedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Definition    *TaskDefinition        `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandedTask) Reset() {
	*x = ExpandedTask{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandedTask) ProtoMessage() {}

func (x *ExpandedTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandedTask.ProtoReflect.Descriptor instead.
func (*ExpandedTask) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{6}
}

func (x *ExpandedTask) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExpandedTask) GetDefinition() *TaskDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *ExpandedTask) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StringValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValues) Reset() {
	*x = StringValues{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValues) ProtoMessage() {}

func (x *StringValues) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValues.ProtoReflect.Descriptor instead.
func (*StringValues) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{7}
}

func (x *StringValues) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           CommandKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=chronos.v1.CommandKind" json:"kind,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,5,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LogicalTime    int64                  `protobuf:"varint,6,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Definition     *WorkflowDefinition    `protobuf:"bytes,7,opt,name=definition,proto3" json:"definition,omitempty"`
	Output         map[string]string      `protobuf:"bytes,8,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error          string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	WorkerId       string                 `protobuf:"bytes,10,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseExpiresAt int64                  `protobuf:"varint,11,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,12,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	TimerId        string                 `protobuf:"bytes,13,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	Reason         string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	Fanout         []*FanoutItem          `protobuf:"bytes,15,rep,name=fanout,proto3" json:"fanout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{8}
}

func (x *Command) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Command) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Command) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Command) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Command) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Command) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Command) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Command) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Command) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *Command) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Command) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *Command) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Command) GetFanout() []*FanoutItem {
	if x != nil {
		return x.Fanout
	}
	return nil
}

type Event struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Id             string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           EventKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=chronos.v1.EventKind" json:"kind,omitempty"`
	Sequence       uint64                   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RequestId      string                   `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestHash    string                   `protobuf:"bytes,5,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	WorkflowId     string                   `protobuf:"bytes,6,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId         string                   `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId      string                   `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Attempt        uint32                   `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LogicalTime    int64                    `protobuf:"varint,10,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	Definition     *WorkflowDefinition      `protobuf:"bytes,11,opt,name=definition,proto3" json:"definition,omitempty"`
	Inputs         map[string]*StringValues `protobuf:"bytes,12,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Output         map[string]string        `protobuf:"bytes,13,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error          string                   `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	WorkerId       string                   `protobuf:"bytes,15,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseExpiresAt int64                    `protobuf:"varint,16,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	FencingToken   uint64                   `protobuf:"varint,17,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	IdempotencyKey string                   `protobuf:"bytes,18,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Timer          *Timer                   `protobuf:"bytes,19,opt,name=timer,proto3" json:"timer,omitempty"`
	ExpandedTasks  []*ExpandedTask          `protobuf:"bytes,20,rep,name=expanded_tasks,json=expandedTasks,proto3" json:"expanded_tasks,omitempty"`
	Reason         string                   `protobuf:"bytes,21,opt,name=reason,proto3" json:"reason,omitempty"`
	Compensation   bool                     `protobuf:"varint,22,opt,name=compensation,proto3" json:"compensation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Event) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *Event) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Event) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Event) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Event) GetInputs() map[string]*StringValues {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Event) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Event) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Event) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *Event) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Event) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Event) GetTimer() *Timer {
	if x != nil {
		return x.Timer
	}
	return nil
}

func (x *Event) GetExpandedTasks() []*ExpandedTask {
	if x != nil {
		return x.ExpandedTasks
	}
	return nil
}

func (x *Event) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Event) GetCompensation() bool {
	if x != nil {
		return x.Compensation
	}
	return false
}

type Timer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Deadline      int64                  `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Status        TimerStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=chronos.v1.TimerStatus" json:"status,omitempty"`
	Purpose       TimerPurpose           `protobuf:"varint,5,opt,name=purpose,proto3,enum=chronos.v1.TimerPurpose" json:"purpose,omitempty"`
	AttemptId     string                 `protobuf:"bytes,6,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,7,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Attempt       uint32                 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timer) Reset() {
	*x = Timer{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timer) ProtoMessage() {}

func (x *Timer) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timer.ProtoReflect.Descriptor instead.
func (*Timer) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{10}
}

func (x *Timer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Timer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Timer) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Timer) GetStatus() TimerStatus {
	if x != nil {
		return x.Status
	}
	return TimerStatus_TIMER_STATUS_UNSPECIFIED
}

func (x *Timer) GetPurpose() TimerPurpose {
	if x != nil {
		return x.Purpose
	}
	return TimerPurpose_TIMER_PURPOSE_UNSPECIFIED
}

func (x *Timer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Timer) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Timer) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Credits       uint32                 `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{11}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *WorkerHello) GetCredits() uint32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

type CreditGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credits       uint32                 `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditGrant) Reset() {
	*x = CreditGrant{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditGrant) ProtoMessage() {}

func (x *CreditGrant) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditGrant.ProtoReflect.Descriptor instead.
func (*CreditGrant) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{12}
}

func (x *CreditGrant) GetCredits() uint32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

type LeaseHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	LeaseExpiresAt int64                  `protobuf:"varint,6,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseHeartbeat) Reset() {
	*x = LeaseHeartbeat{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseHeartbeat) ProtoMessage() {}

func (x *LeaseHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseHeartbeat.ProtoReflect.Descriptor instead.
func (*LeaseHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{13}
}

func (x *LeaseHeartbeat) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LeaseHeartbeat) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LeaseHeartbeat) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LeaseHeartbeat) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LeaseHeartbeat) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseHeartbeat) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

type TaskCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Output        map[string]string      `protobuf:"bytes,6,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Fanout        []*FanoutItem          `protobuf:"bytes,8,rep,name=fanout,proto3" json:"fanout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletion) Reset() {
	*x = TaskCompletion{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletion) ProtoMessage() {}

func (x *TaskCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletion.ProtoReflect.Descriptor instead.
func (*TaskCompletion) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{14}
}

func (x *TaskCompletion) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskCompletion) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TaskCompletion) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletion) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskCompletion) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *TaskCompletion) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskCompletion) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskCompletion) GetFanout() []*FanoutItem {
	if x != nil {
		return x.Fanout
	}
	return nil
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Credit
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Completion
	Value         isWorkerMessage_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{15}
}

func (x *WorkerMessage) GetValue() isWorkerMessage_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WorkerMessage) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Value.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetCredit() *CreditGrant {
	if x != nil {
		if x, ok := x.Value.(*WorkerMessage_Credit); ok {
			return x.Credit
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *LeaseHeartbeat {
	if x != nil {
		if x, ok := x.Value.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetCompletion() *TaskCompletion {
	if x != nil {
		if x, ok := x.Value.(*WorkerMessage_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isWorkerMessage_Value interface {
	isWorkerMessage_Value()
}

type WorkerMessage_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Credit struct {
	Credit *CreditGrant `protobuf:"bytes,2,opt,name=credit,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *LeaseHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Completion struct {
	Completion *TaskCompletion `protobuf:"bytes,4,opt,name=completion,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Value() {}

func (*WorkerMessage_Credit) isWorkerMessage_Value() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Value() {}

func (*WorkerMessage_Completion) isWorkerMessage_Value() {}

type TaskAssignment struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	WorkflowId     string                   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId         string                   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType       string                   `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	AttemptId      string                   `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Attempt        uint32                   `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	WorkerId       string                   `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseExpiresAt int64                    `protobuf:"varint,7,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	FencingToken   uint64                   `protobuf:"varint,8,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	IdempotencyKey string                   `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Inputs         map[string]*StringValues `protobuf:"bytes,10,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Compensation   bool                     `protobuf:"varint,11,opt,name=compensation,proto3" json:"compensation,omitempty"`
	Payload        map[string]string        `protobuf:"bytes,12,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{16}
}

func (x *TaskAssignment) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskAssignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskAssignment) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskAssignment) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskAssignment) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *TaskAssignment) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *TaskAssignment) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskAssignment) GetInputs() map[string]*StringValues {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TaskAssignment) GetCompensation() bool {
	if x != nil {
		return x.Compensation
	}
	return false
}

func (x *TaskAssignment) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WorkerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerAck) Reset() {
	*x = WorkerAck{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerAck) ProtoMessage() {}

func (x *WorkerAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerAck.ProtoReflect.Descriptor instead.
func (*WorkerAck) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{17}
}

func (x *WorkerAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *WorkerAck) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *WorkerAck) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WorkerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*CoordinatorMessage_Assignment
	//	*CoordinatorMessage_Ack
	Value         isCoordinatorMessage_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_chronos_v1_chronos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_api_chronos_v1_chronos_proto_rawDescGZIP(), []int{18}
}

func (x *CoordinatorMessage) GetValue() isCoordinatorMessage_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CoordinatorMessage) GetAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Value.(*CoordinatorMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetAck() *WorkerAck {
	if x != nil {
		if x, ok := x.Value.(*CoordinatorMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isCoordinatorMessage_Value interface {
	isCoordinatorMessage_Value()
}

type CoordinatorMessage_Assignment struct {
	Assignment *TaskAssignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

type CoordinatorMessage_Ack struct {
	Ack *WorkerAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*CoordinatorMessage_Assignment) isCoordinatorMessage_Value() {}

func (*CoordinatorMessage_Ack) isCoordinatorMessage_Value() {}

var File_api_chronos_v1_chronos_proto protoreflect.FileDescriptor

const file_api_chronos_v1_chronos_proto_rawDesc = "" +
	"\n" +
	"\x1capi/chronos/v1/chronos.proto\x12\n" +
	"chronos.v1\"\xc3\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\rR\vmaxAttempts\x124\n" +
	"\x16initial_backoff_millis\x18\x02 \x01(\x03R\x14initialBackoffMillis\x12-\n" +
	"\x12backoff_multiplier\x18\x03 \x01(\rR\x11backoffMultiplier\x12,\n" +
	"\x12max_backoff_millis\x18\x04 \x01(\x03R\x10maxBackoffMillis\"5\n" +
	"\x16CompensationDefinition\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\"\x96\x02\n" +
	"\x10FanoutDefinition\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12*\n" +
	"\x11aggregate_task_id\x18\x02 \x01(\tR\x0faggregateTaskId\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\rR\bmaxItems\x12-\n" +
	"\x05retry\x18\x04 \x01(\v2\x17.chronos.v1.RetryPolicyR\x05retry\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\x12F\n" +
	"\fcompensation\x18\x06 \x01(\v2\".chronos.v1.CompensationDefinitionR\fcompensation\"\xac\x02\n" +
	"\x0eTaskDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\fdependencies\x18\x03 \x03(\tR\fdependencies\x12-\n" +
	"\x05retry\x18\x04 \x01(\v2\x17.chronos.v1.RetryPolicyR\x05retry\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\x12F\n" +
	"\fcompensation\x18\x06 \x01(\v2\".chronos.v1.CompensationDefinitionR\fcompensation\x124\n" +
	"\x06fanout\x18\a \x01(\v2\x1c.chronos.v1.FanoutDefinitionR\x06fanout\"\x93\x01\n" +
	"\x12WorkflowDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x120\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1a.chronos.v1.TaskDefinitionR\x05tasks\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\x03R\astartAt\"\x99\x01\n" +
	"\n" +
	"FanoutItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\apayload\x18\x02 \x03(\v2#.chronos.v1.FanoutItem.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\fExpandedTask\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x1a.chronos.v1.TaskDefinitionR\n" +
	"definition\x12?\n" +
	"\apayload\x18\x03 \x03(\v2%.chronos.v1.ExpandedTask.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\fStringValues\x12<\n" +
	"\x06values\x18\x01 \x03(\v2$.chronos.v1.StringValues.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x04\n" +
	"\aCommand\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.chronos.v1.CommandKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x05 \x01(\tR\tattemptId\x12!\n" +
	"\flogical_time\x18\x06 \x01(\x03R\vlogicalTime\x12>\n" +
	"\n" +
	"definition\x18\a \x01(\v2\x1e.chronos.v1.WorkflowDefinitionR\n" +
	"definition\x127\n" +
	"\x06output\x18\b \x03(\v2\x1f.chronos.v1.Command.OutputEntryR\x06output\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1b\n" +
	"\tworker_id\x18\n" +
	" \x01(\tR\bworkerId\x12(\n" +
	"\x10lease_expires_at\x18\v \x01(\x03R\x0eleaseExpiresAt\x12#\n" +
	"\rfencing_token\x18\f \x01(\x04R\ffencingToken\x12\x19\n" +
	"\btimer_id\x18\r \x01(\tR\atimerId\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x12.\n" +
	"\x06fanout\x18\x0f \x03(\v2\x16.chronos.v1.FanoutItemR\x06fanout\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\a\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.chronos.v1.EventKindR\x04kind\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12!\n" +
	"\frequest_hash\x18\x05 \x01(\tR\vrequestHash\x12\x1f\n" +
	"\vworkflow_id\x18\x06 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tR\tattemptId\x12\x18\n" +
	"\aattempt\x18\t \x01(\rR\aattempt\x12!\n" +
	"\flogical_time\x18\n" +
	" \x01(\x03R\vlogicalTime\x12>\n" +
	"\n" +
	"definition\x18\v \x01(\v2\x1e.chronos.v1.WorkflowDefinitionR\n" +
	"definition\x125\n" +
	"\x06inputs\x18\f \x03(\v2\x1d.chronos.v1.Event.InputsEntryR\x06inputs\x125\n" +
	"\x06output\x18\r \x03(\v2\x1d.chronos.v1.Event.OutputEntryR\x06output\x12\x14\n" +
	"\x05error\x18\x0e \x01(\tR\x05error\x12\x1b\n" +
	"\tworker_id\x18\x0f \x01(\tR\bworkerId\x12(\n" +
	"\x10lease_expires_at\x18\x10 \x01(\x03R\x0eleaseExpiresAt\x12#\n" +
	"\rfencing_token\x18\x11 \x01(\x04R\ffencingToken\x12'\n" +
	"\x0fidempotency_key\x18\x12 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x05timer\x18\x13 \x01(\v2\x11.chronos.v1.TimerR\x05timer\x12?\n" +
	"\x0eexpanded_tasks\x18\x14 \x03(\v2\x18.chronos.v1.ExpandedTaskR\rexpandedTasks\x12\x16\n" +
	"\x06reason\x18\x15 \x01(\tR\x06reason\x12\"\n" +
	"\fcompensation\x18\x16 \x01(\bR\fcompensation\x1aS\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.chronos.v1.StringValuesR\x05value:\x028\x01\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x05Timer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bdeadline\x18\x03 \x01(\x03R\bdeadline\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.chronos.v1.TimerStatusR\x06status\x122\n" +
	"\apurpose\x18\x05 \x01(\x0e2\x18.chronos.v1.TimerPurposeR\apurpose\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x06 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\a \x01(\x04R\ffencingToken\x12\x18\n" +
	"\aattempt\x18\b \x01(\rR\aattempt\"h\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x18\n" +
	"\acredits\x18\x03 \x01(\rR\acredits\"'\n" +
	"\vCreditGrant\x12\x18\n" +
	"\acredits\x18\x01 \x01(\rR\acredits\"\xd7\x01\n" +
	"\x0eLeaseHeartbeat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x04R\ffencingToken\x12(\n" +
	"\x10lease_expires_at\x18\x06 \x01(\x03R\x0eleaseExpiresAt\"\xee\x02\n" +
	"\x0eTaskCompletion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x04R\ffencingToken\x12>\n" +
	"\x06output\x18\x06 \x03(\v2&.chronos.v1.TaskCompletion.OutputEntryR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12.\n" +
	"\x06fanout\x18\b \x03(\v2\x16.chronos.v1.FanoutItemR\x06fanout\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\rWorkerMessage\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.chronos.v1.WorkerHelloH\x00R\x05hello\x121\n" +
	"\x06credit\x18\x02 \x01(\v2\x17.chronos.v1.CreditGrantH\x00R\x06credit\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.chronos.v1.LeaseHeartbeatH\x00R\theartbeat\x12<\n" +
	"\n" +
	"completion\x18\x04 \x01(\v2\x1a.chronos.v1.TaskCompletionH\x00R\n" +
	"completionB\a\n" +
	"\x05value\"\xed\x04\n" +
	"\x0eTaskAssignment\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\rR\aattempt\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\x12(\n" +
	"\x10lease_expires_at\x18\a \x01(\x03R\x0eleaseExpiresAt\x12#\n" +
	"\rfencing_token\x18\b \x01(\x04R\ffencingToken\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12>\n" +
	"\x06inputs\x18\n" +
	" \x03(\v2&.chronos.v1.TaskAssignment.InputsEntryR\x06inputs\x12\"\n" +
	"\fcompensation\x18\v \x01(\bR\fcompensation\x12A\n" +
	"\apayload\x18\f \x03(\v2'.chronos.v1.TaskAssignment.PayloadEntryR\apayload\x1aS\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.chronos.v1.StringValuesR\x05value:\x028\x01\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\tWorkerAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x86\x01\n" +
	"\x12CoordinatorMessage\x12<\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1a.chronos.v1.TaskAssignmentH\x00R\n" +
	"assignment\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.chronos.v1.WorkerAckH\x00R\x03ackB\a\n" +
	"\x05value*\x8a\x02\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x04\x12 \n" +
	"\x1cWORKFLOW_STATUS_COMPENSATING\x10\x05\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_COMPENSATED\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_SCHEDULED\x10\a*\xfb\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11TASK_STATUS_READY\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x06\x12\x1c\n" +
	"\x18TASK_STATUS_COMPENSATING\x10\a\x12\x1b\n" +
	"\x17TASK_STATUS_COMPENSATED\x10\b*{\n" +
	"\vTimerStatus\x12\x1c\n" +
	"\x18TIMER_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TIMER_STATUS_SCHEDULED\x10\x01\x12\x16\n" +
	"\x12TIMER_STATUS_FIRED\x10\x02\x12\x1a\n" +
	"\x16TIMER_STATUS_CANCELLED\x10\x03*\x83\x01\n" +
	"\fTimerPurpose\x12\x1d\n" +
	"\x19TIMER_PURPOSE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTIMER_PURPOSE_WORKFLOW_START\x10\x01\x12\x17\n" +
	"\x13TIMER_PURPOSE_RETRY\x10\x02\x12\x19\n" +
	"\x15TIMER_PURPOSE_TIMEOUT\x10\x03*\xa2\x02\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCOMMAND_KIND_SUBMIT_WORKFLOW\x10\x01\x12\x1b\n" +
	"\x17COMMAND_KIND_START_TASK\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_KIND_COMPLETE_TASK\x10\x03\x12\x1a\n" +
	"\x16COMMAND_KIND_FAIL_TASK\x10\x04\x12\x1c\n" +
	"\x18COMMAND_KIND_RENEW_LEASE\x10\x05\x12\x1d\n" +
	"\x19COMMAND_KIND_EXPIRE_LEASE\x10\x06\x12\x1b\n" +
	"\x17COMMAND_KIND_FIRE_TIMER\x10\a\x12 \n" +
	"\x1cCOMMAND_KIND_CANCEL_WORKFLOW\x10\b*\x85\x06\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dEVENT_KIND_WORKFLOW_SUBMITTED\x10\x01\x12\x19\n" +
	"\x15EVENT_KIND_TASK_READY\x10\x02\x12\x1b\n" +
	"\x17EVENT_KIND_TASK_STARTED\x10\x03\x12\x1d\n" +
	"\x19EVENT_KIND_TASK_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16EVENT_KIND_TASK_FAILED\x10\x05\x12!\n" +
	"\x1dEVENT_KIND_WORKFLOW_COMPLETED\x10\x06\x12\x1e\n" +
	"\x1aEVENT_KIND_WORKFLOW_FAILED\x10\a\x12!\n" +
	"\x1dEVENT_KIND_TASK_LEASE_RENEWED\x10\b\x12!\n" +
	"\x1dEVENT_KIND_TASK_LEASE_EXPIRED\x10\t\x12\x1f\n" +
	"\x1bEVENT_KIND_WORKFLOW_STARTED\x10\n" +
	"\x12\x1e\n" +
	"\x1aEVENT_KIND_FANOUT_EXPANDED\x10\v\x12\x1e\n" +
	"\x1aEVENT_KIND_TIMER_SCHEDULED\x10\f\x12\x1a\n" +
	"\x16EVENT_KIND_TIMER_FIRED\x10\r\x12\x1e\n" +
	"\x1aEVENT_KIND_TIMER_CANCELLED\x10\x0e\x12#\n" +
	"\x1fEVENT_KIND_TASK_RETRY_SCHEDULED\x10\x0f\x12\x1d\n" +
	"\x19EVENT_KIND_TASK_TIMED_OUT\x10\x10\x12\x1d\n" +
	"\x19EVENT_KIND_TASK_CANCELLED\x10\x11\x12.\n" +
	"*EVENT_KIND_WORKFLOW_CANCELLATION_REQUESTED\x10\x12\x12$\n" +
	" EVENT_KIND_WORKFLOW_COMPENSATING\x10\x13\x12\x1f\n" +
	"\x1bEVENT_KIND_TASK_COMPENSATED\x10\x14\x12!\n" +
	"\x1dEVENT_KIND_WORKFLOW_CANCELLED\x10\x15\x12#\n" +
	"\x1fEVENT_KIND_WORKFLOW_COMPENSATED\x10\x162V\n" +
	"\rWorkerService\x12E\n" +
	"\x04Work\x12\x19.chronos.v1.WorkerMessage\x1a\x1e.chronos.v1.CoordinatorMessage(\x010\x01BAZ?github.com/HaikIsaiants/chronos-public/api/chronos/v1;chronosv1b\x06proto3"

var (
	file_api_chronos_v1_chronos_proto_rawDescOnce sync.Once
	file_api_chronos_v1_chronos_proto_rawDescData []byte
)

func file_api_chronos_v1_chronos_proto_rawDescGZIP() []byte {
	file_api_chronos_v1_chronos_proto_rawDescOnce.Do(func() {
		file_api_chronos_v1_chronos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chronos_v1_chronos_proto_rawDesc), len(file_api_chronos_v1_chronos_proto_rawDesc)))
	})
	return file_api_chronos_v1_chronos_proto_rawDescData
}

var file_api_chronos_v1_chronos_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_chronos_v1_chronos_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_chronos_v1_chronos_proto_goTypes = []any{
	(WorkflowStatus)(0),            // 0: chronos.v1.WorkflowStatus
	(TaskStatus)(0),                // 1: chronos.v1.TaskStatus
	(TimerStatus)(0),               // 2: chronos.v1.TimerStatus
	(TimerPurpose)(0),              // 3: chronos.v1.TimerPurpose
	(CommandKind)(0),               // 4: chronos.v1.CommandKind
	(EventKind)(0),                 // 5: chronos.v1.EventKind
	(*RetryPolicy)(nil),            // 6: chronos.v1.RetryPolicy
	(*CompensationDefinition)(nil), // 7: chronos.v1.CompensationDefinition
	(*FanoutDefinition)(nil),       // 8: chronos.v1.FanoutDefinition
	(*TaskDefinition)(nil),         // 9: chronos.v1.TaskDefinition
	(*WorkflowDefinition)(nil),     // 10: chronos.v1.WorkflowDefinition
	(*FanoutItem)(nil),             // 11: chronos.v1.FanoutItem
	(*ExpandedTask)(nil),           // 12: chronos.v1.ExpandedTask
	(*StringValues)(nil),           // 13: chronos.v1.StringValues
	(*Command)(nil),                // 14: chronos.v1.Command
	(*Event)(nil),                  // 15: chronos.v1.Event
	(*Timer)(nil),                  // 16: chronos.v1.Timer
	(*WorkerHello)(nil),            // 17: chronos.v1.WorkerHello
	(*CreditGrant)(nil),            // 18: chronos.v1.CreditGrant
	(*LeaseHeartbeat)(nil),         // 19: chronos.v1.LeaseHeartbeat
	(*TaskCompletion)(nil),         // 20: chronos.v1.TaskCompletion
	(*WorkerMessage)(nil),          // 21: chronos.v1.WorkerMessage
	(*TaskAssignment)(nil),         // 22: chronos.v1.TaskAssignment
	(*WorkerAck)(nil),              // 23: chronos.v1.WorkerAck
	(*CoordinatorMessage)(nil),     // 24: chronos.v1.CoordinatorMessage
	nil,                            // 25: chronos.v1.FanoutItem.PayloadEntry
	nil,                            // 26: chronos.v1.ExpandedTask.PayloadEntry
	nil,                            // 27: chronos.v1.StringValues.ValuesEntry
	nil,                            // 28: chronos.v1.Command.OutputEntry
	nil,                            // 29: chronos.v1.Event.InputsEntry
	nil,                            // 30: chronos.v1.Event.OutputEntry
	nil,                            // 31: chronos.v1.TaskCompletion.OutputEntry
	nil,                            // 32: chronos.v1.TaskAssignment.InputsEntry
	nil,                            // 33: chronos.v1.TaskAssignment.PayloadEntry
}
var file_api_chronos_v1_chronos_proto_depIdxs = []int32{
	6,  // 0: chronos.v1.FanoutDefinition.retry:type_name -> chronos.v1.RetryPolicy
	7,  // 1: chronos.v1.FanoutDefinition.compensation:type_name -> chronos.v1.CompensationDefinition
	6,  // 2: chronos.v1.TaskDefinition.retry:type_name -> chronos.v1.RetryPolicy
	7,  // 3: chronos.v1.TaskDefinition.compensation:type_name -> chronos.v1.CompensationDefinition
	8,  // 4: chronos.v1.TaskDefinition.fanout:type_name -> chronos.v1.FanoutDefinition
	9,  // 5: chronos.v1.WorkflowDefinition.tasks:type_name -> chronos.v1.TaskDefinition
	25, // 6: chronos.v1.FanoutItem.payload:type_name -> chronos.v1.FanoutItem.PayloadEntry
	9,  // 7: chronos.v1.ExpandedTask.definition:type_name -> chronos.v1.TaskDefinition
	26, // 8: chronos.v1.ExpandedTask.payload:type_name -> chronos.v1.ExpandedTask.PayloadEntry
	27, // 9: chronos.v1.StringValues.values:type_name -> chronos.v1.StringValues.ValuesEntry
	4,  // 10: chronos.v1.Command.kind:type_name -> chronos.v1.CommandKind
	10, // 11: chronos.v1.Command.definition:type_name -> chronos.v1.WorkflowDefinition
	28, // 12: chronos.v1.Command.output:type_name -> chronos.v1.Command.OutputEntry
	11, // 13: chronos.v1.Command.fanout:type_name -> chronos.v1.FanoutItem
	5,  // 14: chronos.v1.Event.kind:type_name -> chronos.v1.EventKind
	10, // 15: chronos.v1.Event.definition:type_name -> chronos.v1.WorkflowDefinition
	29, // 16: chronos.v1.Event.inputs:type_name -> chronos.v1.Event.InputsEntry
	30, // 17: chronos.v1.Event.output:type_name -> chronos.v1.Event.OutputEntry
	16, // 18: chronos.v1.Event.timer:type_name -> chronos.v1.Timer
	12, // 19: chronos.v1.Event.expanded_tasks:type_name -> chronos.v1.ExpandedTask
	2,  // 20: chronos.v1.Timer.status:type_name -> chronos.v1.TimerStatus
	3,  // 21: chronos.v1.Timer.purpose:type_name -> chronos.v1.TimerPurpose
	31, // 22: chronos.v1.TaskCompletion.output:type_name -> chronos.v1.TaskCompletion.OutputEntry
	11, // 23: chronos.v1.TaskCompletion.fanout:type_name -> chronos.v1.FanoutItem
	17, // 24: chronos.v1.WorkerMessage.hello:type_name -> chronos.v1.WorkerHello
	18, // 25: chronos.v1.WorkerMessage.credit:type_name -> chronos.v1.CreditGrant
	19, // 26: chronos.v1.WorkerMessage.heartbeat:type_name -> chronos.v1.LeaseHeartbeat
	20, // 27: chronos.v1.WorkerMessage.completion:type_name -> chronos.v1.TaskCompletion
	32, // 28: chronos.v1.TaskAssignment.inputs:type_name -> chronos.v1.TaskAssignment.InputsEntry
	33, // 29: chronos.v1.TaskAssignment.payload:type_name -> chronos.v1.TaskAssignment.PayloadEntry
	22, // 30: chronos.v1.CoordinatorMessage.assignment:type_name -> chronos.v1.TaskAssignment
	23, // 31: chronos.v1.CoordinatorMessage.ack:type_name -> chronos.v1.WorkerAck
	13, // 32: chronos.v1.Event.InputsEntry.value:type_name -> chronos.v1.StringValues
	13, // 33: chronos.v1.TaskAssignment.InputsEntry.value:type_name -> chronos.v1.StringValues
	21, // 34: chronos.v1.WorkerService.Work:input_type -> chronos.v1.WorkerMessage
	24, // 35: chronos.v1.WorkerService.Work:output_type -> chronos.v1.CoordinatorMessage
	35, // [35:36] is the sub-list for method output_type
	34, // [34:35] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_chronos_v1_chronos_proto_init() }
func file_api_chronos_v1_chronos_proto_init() {
	if File_api_chronos_v1_chronos_proto != nil {
		return
	}
	file_api_chronos_v1_chronos_proto_msgTypes[15].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Credit)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Completion)(nil),
	}
	file_api_chronos_v1_chronos_proto_msgTypes[18].OneofWrappers = []any{
		(*CoordinatorMessage_Assignment)(nil),
		(*CoordinatorMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chronos_v1_chronos_proto_rawDesc), len(file_api_chronos_v1_chronos_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chronos_v1_chronos_proto_goTypes,
		DependencyIndexes: file_api_chronos_v1_chronos_proto_depIdxs,
		EnumInfos:         file_api_chronos_v1_chronos_proto_enumTypes,
		MessageInfos:      file_api_chronos_v1_chronos_proto_msgTypes,
	}.Build()
	File_api_chronos_v1_chronos_proto = out.File
	file_api_chronos_v1_chronos_proto_goTypes = nil
	file_api_chronos_v1_chronos_proto_depIdxs = nil
}
